### ISSUE TITLE
parse_bookshelves() fails due to encoding issue

### ISSUE THREAD

**Issue by fontclos** [pgcorpus/gutenberg#25]
When running `python get_data.py` on Ubuntu 18.10

```bash
> python get_data.py
[ ... ] # bookshelves download step works just fine
FINISHED --2019-01-12 15:51:05--
Total wall clock time: 2m 25s
Downloaded: 518 files, 17M in 8.3s (2.06 MB/s)
Traceback (most recent call last):
  File "get_data.py", line 142, in <module>
    bookshelves_df = parse_bookshelves()
  File "/home/fontclos/work/ongoing/gutenberg/src/bookshelves.py", line 57, in parse_bookshelves
    dom = lxml.html.fromstring(foo.read())
  File "/home/fontclos/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8897: ordinal not in range(128)
```

**Comment by fontclos** [comment]
Instead, no problem when running it on my macbook.
