### ISSUE TITLE
File not found on Windows 10

### ISSUE THREAD

**Issue by luigiusai** [pgcorpus/gutenberg#34]
Hi Martin! Exceptional work.
I show you my shell error:
python3 get_data.py
Traceback (most recent call last):
  File "get_data.py", line 107, in <module>
    subprocess.call(sp_args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

**Comment by fontclos** [comment]
Hi, thanks for your feedback! 
This looks related to the subprocess call at line 107 of get_data.py
```
    sp_args = ["rsync", "-am%s" % vstring,
               "--include", "*/",
               "--include", "[p123456789][g0123456789]%s[.-][t0][x.]t[x.]*[t8]" % args.pattern,
               "--exclude", "*",
               "aleph.gutenberg.org::gutenberg", args.mirror
               ]
    subprocess.call(sp_args)
```
which might indicate you do not have rsync on your system?

**Comment by fontclos** [comment]
could be related to #30

**Comment by fontclos** [comment]
closing because seems related to missing rsync
